InseeFr/Stromae

insee-overload/common/WEB-INF/orbeon-insee/css/commonEnglish.css

update margins into commonEnglish.css

commonEnglish.css headband height

---

insee-overload/common/WEB-INF/orbeon-overload/apps/fr/theme.xsl

- download pdf in new tab for all context

Change url of pdf export for household

---

package-lock.json
package.json
src/App.css

All new Azure tickets (482 - 491)

fix: first returns

---

package.json
src/App.js
src/components/auth/provider/oidc.js
src/components/designSystem/AppVersion.js
src/components/genericPages/end.js
src/components/genericPages/validation.js
src/components/modals/assistance/assistance.js
src/components/modals/sendingConfirmation/sendingConfirmation.js
src/components/modals/welcomeBack/welcomeBack.js
src/components/navigation/burgerMenu/burgerMenu.css
src/components/navigation/burgerMenu/burgerMenu.js
src/components/orchestrator/collector/index.js
src/components/orchestrator/manager/orchestratorManager.js
src/components/orchestrator/navigation/navigation.js
src/components/orchestrator/visualizer/visualizer.js
src/components/shared/error/ErrorFallback.js
src/components/shared/error/index.js
src/i18n/dictionary.js
src/i18n/errorMessage.js
src/utils/api/index.js
src/utils/app/index.js
src/utils/constants/index.js
src/utils/constants/paradata.js
src/utils/events/cookie.js
src/utils/events/logger.js
src/utils/events/paradata.js
src/utils/hooks/api.js
src/utils/hooks/auth.js
src/utils/oidc/build-configuration.js
yarn.lock

- 🆕 feature : handling paradata
- handling error with an ErrorBoundary arround all the app

Add paradata handling event

---

package.json
public/static/questionnaire/simpsons/form.json
public/static/questionnaire/tic/form.json
src/components/genericPages/welcome.js
src/components/orchestrator/collector/index.js
src/components/orchestrator/manager/orchestratorManager.js
src/components/orchestrator/visualizer/questionnaireForm/questionnaireForm.js
src/components/orchestrator/visualizer/visualizer.js
src/i18n/genericPages/welcome.js
src/i18n/visualizeMessage.js
src/utils/events/cookie.js
src/utils/events/logger.js
src/utils/hooks/index.js
src/utils/hooks/questionnaire.js
src/utils/personalization/index.js
src/utils/questionnaire/index.js

- add readonly mode in vizu
- handle missing values in welcome page
- fix date in endPage
- update questionnaire examples

Fix some issues

---

insee-overload/common/WEB-INF/orbeon-insee/services/personalization/personalization.xpl
insee-overload/common/WEB-INF/orbeon-insee/services/redirect.xpl

call to WebServices with apps/Pilotage or apps/orbeon

restXq-exit

---

insee-overload/common/WEB-INF/orbeon-insee/config/properties-local.xml
insee-overload/common/WEB-INF/orbeon-overload/apps/fr/theme.xsl
pom.xml

Modifying the label "Visualiser le questionnaire PDF" in "Exemple de questionnaire"

Label change for a button

---

insee-overload/common/WEB-INF/orbeon-insee/css/commonEnglish.css
insee-overload/common/WEB-INF/orbeon-overload/apps/fr/theme.xsl

addinf a footer in the questionnaires

adding footer

---

.github/workflows/develop-release.yml

Adding docker image building for release candidates (develop branch)

adding image build for develop

---

insee-overload/common/WEB-INF/orbeon-insee/css/commonEnglish.css
insee-overload/common/WEB-INF/orbeon-overload/apps/fr/theme.xsl
pom.xml

@sai6077 @ORogel 
branch for a footer in the questionnaires

Stromae footer

---

package.json
src/components/orchestrator/collector/index.js

Try to fix problem with stateData

build: upgrade version

---

mock-api/api/questionnaire/recensement/source.json
mock-api/api/questionnaire/recensement/source_.json

juste un nouveau json pour tester le rp. sans impact ailleurs.

change source test for rp

---

package.json
src/components/auth/provider/component.js

Sur les conseils de Laurent : 
La redirection à la déconnexion se base sur l'URL du portail de promotion (qui est dans le fichier configuration.json). Le nom de cette variable est portail et non urlPortail
Cette correction devrait suffire

Correction bug stromae pour lors de la déconnexion

---

public/OidcServiceWorker.js
src/components/formulaire/Formulaire.tsx
src/components/orchestrator/Orchestrator.tsx
src/components/orchestrator/UseLunatic.tsx
src/pages/questionnaire/Questionnaire.tsx

Les derniers éléments de configuration pour useLunatic :
- preferences
- features
- savingType
- autoSuggesterLoading
En espérant ne rien oublier

V3 orchestrator rest

---

src/components/Grid/Grid.tsx
src/pages/questionnaire/Questionnaire.tsx

Un composant Grid, pour ajouter la grille responsive au mileir de l'orchestrateur, sans géner la descente de l'interface de l'orchestrateur dans l'arbre de composant.

a grid component for Julia!

---

src/components/navigation/Continuer.tsx
src/components/orchestrator/Saving/SaveOnSequence.tsx
src/lib/commons/isComponentscontainSequence.ts

le bouton continuer affiche commencer lorsqu'une séquence est présente dans la page

continuer or commencer

---

.env
src/components/orchestrator/Saving/SaveOnPage.tsx
src/components/orchestrator/Saving/SaveOnSequence.tsx
src/components/orchestrator/Saving/useSaving.ts

renommage de variable d'env pour fonctionner avec react app

rename var conf for react app

---

src/pages/deconnexion/Deconnexion.tsx
src/typeStromae/type.ts

La possibilité de se reconnecter avec le bouton se reconnecter sur la page /.../deconnexion

re login after logout

---

src/components/AlertesControles/AlertesControles.tsx

Focus sur l'alerte de contrôle des erreurs

V3 focus errors

---

src/components/navigation/Precedent.tsx
src/lib/commons/usePrevious.ts

le focus sur le premier champ input est dur à faire, avec des pages où le contenu change en cour d'usage.
on focus le bouton précédant au changement de page

focus on first button prec

---

src/components/formulaire/Formulaire.tsx

un oublie de suppression de code

remove useEffect for focus

---

mock-api/api/survey-unit/RPSMART/data.json
src/components/ContinueOrRestart/ContinueOrRestart.tsx
src/components/ContinueOrRestart/ModalContinueOrRestart.tsx
src/components/ContinueOrRestart/ModalDsfr.tsx
src/components/navigation/Precedent.tsx
src/components/orchestrator/UseLunatic.tsx
src/lib/commons/parsePageTag.ts
src/lib/commons/useTabulate.ts
src/pages/questionnaire/Questionnaire.tsx
src/typeStromae/type.ts

the modal for restart or continu

modal for continue or restart

---

src/components/ContinueOrRestart/ContinueOrRestart.tsx

merci Jonathan, du code en moins !

simplification currentPage

---

mock-api/api/questionnaire/recensement/source.json
public/rp/source.json
src/components/AlertesControles/AlertesControles.tsx
src/components/Header/Header.tsx
src/components/layout/Main.tsx
yarn.lock

add roles on main and alert
add missing aria on alert
replace p by span inside a

fix: html structure for accessibility

---

package.json

montée de version pour lunatic : 2.4.9 -> 2.4.10

v3 to lunatic v2.4.10

---

.env
src/components/ContinueOrRestart/ContinueOrRestart.tsx
src/components/ContinueOrRestart/ModalContinueOrRestart.tsx
yarn.lock

La fonction goTopage prend désormais page en parmi ses paramètres et recharge directement au milieu des boucles et des  pages

integration de la version 2.5.x de lunatic 

---

.env
package.json
public/OidcServiceWorker.js
src/components/Title/Title.tsx
src/components/layout/Layout.tsx
src/components/orchestrator/LoadSourceData.tsx
src/components/orchestrator/Orchestrator.tsx
src/components/orchestrator/UseLunatic.tsx
src/components/orchestrator/useRemote.tsx
src/components/orchestrator/useTitle.tsx
src/lib/surveys/getMetadataSurvey.ts
src/pages/questionnaire/Questionnaire.tsx
src/typeLunatic/type-source.ts
src/typeStromae/type.ts
yarn.lock

extrait le title (label.value pour le moment) des sequence pour l'affecter à document.title dans le questionnaire.

V3 - in questionnaire, extract title from Sequence

---

package.json
yarn.lock

juste une montée de version de lunatic

update lunatic v + patch type serviceTitle

---

src/components/orchestrator/UseLunatic.tsx

force type of title

---

src/components/ContinueOrRestart/ModalContinueOrRestart.tsx
src/components/DraftBanner/SaveMessage.tsx
src/components/Header/Header.tsx

- The modal's theme was missing (??!)
- We were missing the target props in the header links
- We were missing an aria-hidden attribute on the banner icon.
- I fixed a typo on the modal

fix header link target

---

src/components/DraftBanner/DraftBanner.tsx

Timeout was incorrectly typed and used NodeJS typing

Chore : Remove NodeJS type

---

src/components/ContinueOrRestart/ContinueOrRestart.tsx
src/components/orchestrator/Saving/SaveOnPage.tsx
src/components/orchestrator/Saving/SaveOnSequence.tsx
src/components/orchestrator/Saving/useSaving.ts
src/components/orchestrator/UseLunatic.tsx
src/typeStromae/type.ts

Revert "Fix/v3 save on next page"

---

mock-api/api/questionnaire/recensement/metadata/parametres.json
public/rp/metadata.json
public/rp/parametres.json
src/components/Header/Header.tsx
src/components/Header/default-header.ts
src/components/Oidc/AuthenticatingError.tsx
src/components/Oidc/SessionLost.tsx
src/components/OptionalPage/elements/Title.tsx
src/components/Welcome/WelcomeQuestions.tsx
src/components/Welcome/WelcomeType.ts
src/components/footer/Footer.tsx
src/components/postSubmit/AdditionalInformation.tsx
src/index.tsx
src/pages/error/Error.tsx

To make the most of react router and avoid re-render, I replaced all the links with the Link component from react-router-dom. When I could, I also replaced some html elements with react-dsfr components.

feat: use Link Router

---

package.json
src/components/auth/provider/component.js
src/components/orchestrator/collector/index.js
src/components/orchestrator/manager/orchestratorManager.js

- feat: adding minimal SessionLostComponent

Fix: refresh token rerender

---

src/pages/questionnaire/Questionnaire.tsx
src/pages/visualize/VisualizeResources.tsx

Suppression des alertes de contrôle de haut de page

remove component AlertControl

---

src/components/orchestrator/UseLunatic.tsx

Replace state + useEffect with useMemo

Fix infinite loop when no surveyunit data

---

package.json
src/components/Header/Header.tsx
src/components/Welcome/WelcomeContainer.tsx
src/components/footer/Footer.tsx
src/components/navigation/Continuer.tsx
src/components/postSubmit/PostSubmitSurvey.tsx
src/utils/convertContent.tsx
yarn.lock

remove aria-atomic on continue button (useless)
change span to p 
Remove p in double

Fix html validation

---

src/components/orchestrator/UseLunatic.tsx

Revert "Fix infinite loop when no surveyunit data"

---

src/components/AlertesControles/AlertesControles.tsx
src/pages/questionnaire/Questionnaire.tsx

We need to show the ErrorAlert on the roundabout until we have an error state on the roundabout in Lunatic.

display alert controls just for roundabout

---

.env
package.json
src/components/DevOptions/DevOptions.tsx
src/components/DevOptions/index.js
src/components/orchestrator/UseLunatic.tsx
src/components/orchestrator/useSaving/useSaving.ts
src/pages/questionnaire/Questionnaire.tsx
src/utils/read-env-vars.ts
yarn.lock

Pour sauvegarder une valeur, il faut d'abord prendre celle contenu dans lunatic et ne pas ce fier à la valeur renvoyer par onChange.
On pourrait peut-être essayer de lisser le comportement de onChange qui aujourd'hui renvoie un peu n'importe quoi (tien ou non compte du fait qu'on est une itération et qui ferait mieux de se contenter de renvoyer la valeur contenu dans lunatic, sans se poser plus de question)

use getData to collect lunatic value

---

src/components/Oidc/SessionLost.tsx

V3 develop

---

src/lib/surveys/getMetadataSurvey.ts
src/lib/surveys/getSurvey.ts
src/lib/surveys/getSurveyUnit.ts
src/lib/surveys/surveysApi.ts

Après quelques essais infructueux et échange avec Julia, il apprarait que moize est largement suffisant (et simple) pour prévenir de requêtes intenpestives.

simplification & promise with moize
